### ISSUE TITLE
这个unreal程序模块是否可以运行在ubuntu上呢？

### ISSUE THREAD

**Issue by nonlinear1** [UEBoy2019/PCL-For-UnrealEngine4.25#1]
看了你做的这个程序模块很不错，请问你是否在ubuntu上试过呢？

**Comment by VegetableWithChicken** [comment]
您好，我一般不常用邮箱，有重要邮件，请QQ我下，谢谢!

**Comment by nonlinear1** [comment]
你qq多少呢？要是方便，我加一下。

在 2022-12-11 21:48:25，VegetableWithChicken ***@***.***> 写道：


您好，我一般不常用邮箱，有重要邮件，请QQ我下，谢谢!

**Comment by VegetableWithChicken** [comment]
暂时不可以哦，换起来也容易，把库换成linux的就可以了吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月12日(周一) 晚上11:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VegetableWithChicken/PCL-For-UnrealEngine4.25] 这个unreal程序模块是否可以运行在ubuntu上呢？ (Issue #1)




 你qq多少呢？要是方便，我加一下。
 
 在 2022-12-11 21:48:25，VegetableWithChicken ***@***.***&gt; 写道：
 
 
 您好，我一般不常用邮箱，有重要邮件，请QQ我下，谢谢!
